### PR TITLE
fix: Standalone download and installation for Apple m1

### PR DESCRIPTION
**Pull request by obiSerra**
The purpose of this PR is to enable the download and installation of the Standalone binaries for Apple m1 chips (os: `darwin`, arch: `arm64`).

Binaries for Mac OS seem to be already compatible and only a check made via the package.json prevents the download and installation.

I also added a step for downloading and checking the checksum, as the process was failing because the checksum file was not downloaded automatically

### CODE REVIEW

**Comment by konalegi** [comment]
@obiSerra do you know, is this message somehow could be fixed by your PR? 
I have the following issue with docker on m1
```
#9 26.86 error @pact-foundation/pact-node@10.11.11: The CPU architecture "arm64" is incompatible with this module.
```

**Comment by TimothyJones** [comment]
@konalegi The error message is correct, because we don't have binaries for M1 yet. See #264 for details and a workaround.

I'm going to close this for now, because we can't merge it before we support M1.

**Comment by konalegi** [comment]
@TimothyJones Those workarounds don't work for me, because I'm running inside docker which is under arm64. I guess I have to wait for m1 support.

**Comment by TimothyJones** [comment]
@konalegi: We changed direction on this, and pact-node@10.13.1 / pact-core@11.1.0 have this workaround included.

**Pull request closed without merging**
