### PR TITLE
fix: drop support for node 15 and earlier

### PR DESCRIPTION
**Pull request by mefellows**
This might actually be best being a `fix!` and a new major version. I'm actually unclear on the appropriate semver bump required for this.

### CODE REVIEW

**Comment by YOU54F** [comment]
>This might actually be best being a fix! and a new major version. I'm actually unclear on the appropriate semver bump required for this.

@TimothyJones has suggested exactly that, breaking change and major semver bump (can't find the exact comments but they are around)

Relates to https://github.com/pact-foundation/pact-js/issues/1028

Have updated. also removed the erroneous comment as mentioned in the last PR and updated cirrus ci, to not run after the release has been committed back to git, this matches up with github

**Review by YOU54F — APPROVED** [review]
Thanks Matt, have updated to force a major version bump, with `fix!` so will get this released now.

**Comment by TimothyJones** [comment]
Breaking change, so yes, needs a major bump. Nice work.

I think it’s a good general practice to follow the Bodens release schedule

**Comment by mefellows** [comment]
> Breaking change, so yes, needs a major bump. Nice work.

Agree in general. I think where it was a grey area for me, is that we have dropped support for previous versions but never officially via the `engines` flag. So it would have failed, just in a way that wasn't a first class "unsupported" failure. 

But I think it's good to be explicit. We'll need to major bump Pact JS if this gets pulled in then also.

**Pull request merged**
